apiVersion: v1
kind: Template

labels:
  application: ${APPLICATION_NAME}

metadata:
  name: mlflow-experiment-job

parameters:
- description: Application name
  from: "experiment-run-[a-z0-9]{4}"
  generate: expression
  name: APPLICATION_NAME
  required: true
- name: MLFLOW_TRACKING_URI
  value: http://$(MLFLOW_SERVER_SERVICE_SERVICE_HOST):$(MLFLOW_SERVER_SERVICE_SERVICE_PORT)
  required: true
  # To use the internal host and port number to connect to the mlflow tracking server
  description: "URI to the MLFlow server. Only required if the MLFlow server is in another Namespace"
- name: APP_IMAGE_URI
  description: "Name of the application image to be pulled from the registry"
  value: "mlflow-experiment-image"
  required: true
- name: APP_IMAGE_TAG
  value: "latest"
  required: true
- name: LIMIT_CPU
  value: "2"
  description: "Limit number of CPUs allocated to the job"
  required: false
- name: LIMIT_MEM
  value: "2G"
  description: "Limit amount of memory allocated to the job"
  required: false
- name: REQUEST_CPU
  value: "1"
  description: "Requested number of CPUs allocated to the job"
  required: false
- name: REQUEST_MEM
  value: "1G"
  description: "Requested amount of memory allocated to the job"
  required: false
- name: FLT_PROM_URL
  description: "URL for the Prometheus Host from where the metric data will be collected"
  required: true
- name: FLT_PROM_ACCESS_TOKEN
  description: "OAuth Token used while communicating with the Prometheus Host"
  required: False
- name: FLT_METRICS_LIST
  description: "List of metrics separated by a ';', on which the model will be trained on"
  required: true
- name: FLT_RETRAINING_INTERVAL_MINUTES
  description: "The duration of metric data that is collected and added to the training data every epoch"
  value: "60"
  required: true
- name: FLT_ROLLING_DATA_WINDOW_SIZE
  description: "a rolling data window on which the model will be trained"
  value: "15d"
  required: true
- name: FLT_DEBUG_MODE
  description: "Enable Verbose logging"
  value: "False"
  required: false
- name: APP_FILE
  description: "python application file name that will be run"
  value: test_model.py
  required: true
- name: NB_USER
  description: "Name of user that will be logged in mlflow"
  value: "unknown"
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
      experiment: ${APP_IMAGE_URI}
  spec:
    template:
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APP_IMAGE_URI}:${APP_IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              memory: ${REQUEST_MEM}
              cpu: ${REQUEST_CPU}
            limits:
              memory: ${LIMIT_MEM}
              cpu: ${LIMIT_CPU}
          env:
          - name: NB_USER
            value: ${NB_USER}
          - name: APP_FILE
            value: ${APP_FILE}
          - name: MLFLOW_TRACKING_URI
            value: ${MLFLOW_TRACKING_URI}
          - name: FLT_PROM_URL
            value: ${FLT_PROM_URL}
          - name: FLT_PROM_ACCESS_TOKEN
            value: ${FLT_PROM_ACCESS_TOKEN}
          - name: FLT_METRICS_LIST
            value: ${FLT_METRICS_LIST}
          - name: FLT_ROLLING_DATA_WINDOW_SIZE
            value: ${FLT_ROLLING_DATA_WINDOW_SIZE}
          - name: FLT_RETRAINING_INTERVAL_MINUTES
            value: ${FLT_RETRAINING_INTERVAL_MINUTES}
          - name: FLT_DEBUG_MODE
            value: ${FLT_DEBUG_MODE}
        restartPolicy: OnFailure
